![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2F2b87ad5d-bd8e-43b8-887e-dd8a76bb2ccb%2Fimage.png)

![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2Fe53ce299-c1d4-4c8c-852a-007489d18236%2Fimage.png)

### Log-Odds
* 개념

> 선형 회귀에서는 각 속성의 값에다가 계수(coefficient)에 각 곱하고 절편(intercept)을 더해서 예측 값(-∞에서 + ∞)을 구함.

> 로지스틱 회귀에서는 마지막에 예측 값 대신 log-odds를 구함.

![Odds](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2F3b3be5db-abbc-4282-954e-bd804a8e40bb%2Fimage.png)

![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2Fcc675ecd-1322-4668-a84e-afb07e46b85f%2Fimage.png)

![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2F1df981ac-1eb1-4f56-9440-7b69f932d99e%2Fimage.png)

 log-odds를 Sigmoid 함수에 넣어서 0부터 1사이의 값으로 변환

![시그모이드함수](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2Fff158266-10eb-444d-9226-82fb027af98f%2Fimage.png)

###Log Loss(로그 손실)
![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2F5bfc396a-0b59-4a2f-895d-f82507ecc574%2Fimage.png)

![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2F18472b1c-942f-432e-9bc4-a49cefed23ef%2Fimage.png)

![](https://velog.velcdn.com/images%2Fhyesoup%2Fpost%2Fa22d9c78-e23b-44c8-9f0b-90580fac68e6%2Fimage.png)


![](https://quantifyinghealth.com/wp-content/uploads/2021/05/Logistic-regression-equation.png)

![](http://people.linguistics.mcgill.ca/~morgan/qmld-book/04-CDA_files/figure-html/logodds-1.png)

In [ ]:
#드라이브 마운트
#디렉토리 변경

In [ ]:
#1.csv 읽어오기("fish_all.csv")

In [ ]:
#2.특성, 정답 구분

In [ ]:
#3.특성 데이터를 훈련/테스트 데이터로 분리

In [ ]:
#훈련/테스트 데이터 표준화(전처리)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

z = np.arange(-5, 5, 0.1)
phi = 1/(1+np.exp(-z))
plt.plot(z, phi)
plt.xlabel("z")
plt.ylabel("phi")
plt.show()

### 이항분류

In [ ]:
#표준 훈련데이터에서 'Bream'과 'Smelt'데이터만 추출

In [ ]:
#표준 테스트데이터에서 'Bream'과 'Smelt'데이터만 추출

In [ ]:
#4.모델 훈련 및 정확도(LogisticRegression)

In [ ]:
#5.테스트데이터로 결과 예측(5행의 데이터만 표시)

In [ ]:
#테스트데이터로 결과 확인

In [ ]:
#클래스 확률값 표시(predict_proba)

In [ ]:
[0.02544183 0.00467123 0.00439073 0.00129744 0.00526059]

In [ ]:
#모델의 기울기와 절편값(coef_, intercept_)

In [ ]:
#클래스 유형(classes_)

In [ ]:
z_value = model.decision_function(test_scaled2[:5])
print(z_value)

In [ ]:
from scipy.special import expit
print(expit(z_value))

### 다항분류

In [ ]:
#4.모델 훈련 및 정확도(LogisticRegression(C=20, max_iter=1000)) #기본값:C=1(값이 클수록 강도가 약함), max_iter=100

In [ ]:
#클래스 유형(classes_)

In [ ]:
#5.테스트데이터로 결과 예측(5행의 데이터만 표시)

In [ ]:
#테스트데이터로 결과 확인

In [ ]:
#클래스 확률값 표시(predict_proba):5행만

In [ ]:
[[0.    0.029 0.237 0.003 0.685 0.01  0.035]
 [0.    0.032 0.576 0.001 0.35  0.003 0.039]
 [0.    0.062 0.558 0.001 0.336 0.017 0.026]
 [0.003 0.93  0.001 0.    0.051 0.    0.015]
 [0.001 0.882 0.004 0.    0.094 0.002 0.017]]

In [ ]:
z_value2 = model2.decision_function(test_scaled[:5])
print(np.round(z_value2, decimals=3))

In [ ]:
from scipy.special import softmax
proba2 = softmax(z_value2, axis=1)
print(np.round(proba2, decimals=3))